import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import {
  ClerkLoaded,
  ClerkLoading,
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Providers } from "./providers";
import { Navbar } from "@/components/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className="bg-black text-white">
          <ClerkLoading>
            <div>Loading.....</div>
          </ClerkLoading>
          <ClerkLoaded>
            <Navbar />
            <div className="max-w-6xl mx-auto">
              <div className="flex flex-col h-screen text-5xl">{children}</div>
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </Providers>
  );
}
